name: CI - Pull Request from Upstream

on:
  push:
    branches: 
      - master
#  schedule:
#    - cron: "30 0,2,12 * * *"

jobs:
  pull-request:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2	
      with:	
        repository: marceloctorres/COVID-19 	
        path: target	

    - name: Pull Request Code
      run: |
        cd target
        GITHUB_TOKEN='m4rc3l025202$$'
        echo $GITHUB_TOKEN
         
        echo "git config --global user.name 'marceloctorres'"
        git config --global user.name 'marceloctorres'

        echo "git config --global user.password $GITHUB_TOKEN"
        git config --global user.password $GITHUB_TOKEN
        
        echo 'git config credential.helper store'
        git config credential.helper store
        
        echo 'git config credential.github.com.useHttpPath true'
        git config credential.github.com.useHttpPath true
        
        echo 'git remote -v'
        git remote -v

        echo "git remote set-url origin 'https://marceloctorres:$GITHUB_TOKEN@github.com/marceloctorres/COVID-19.git'"
        git remote set-url origin 'https://marceloctorres:$GITHUB_TOKEN@github.com/marceloctorres/COVID-19.git'
        
        echo "git remote add upstream 'https://github.com/CSSEGISandData/COVID-19.git'"
        git remote add upstream 'https://github.com/CSSEGISandData/COVID-19.git'
        
        echo "git remote add downstream 'https://github.com/marceloctorresnet/COVID-19.git'"
        git remote add downstream 'https://github.com/marceloctorresnet/COVID-19.git'
        
        echo "git remote -v"
        git remote -v
        
        echo "git checkout master"
        git checkout master
        
        echo "git pull upstream master --allow-unrelated-histories"
        git pull upstream master --allow-unrelated-histories
        
        echo "git add ."
        git add .
        
        echo "git commit -m 'Automatizado o manual?'"
        git commit -m 'Automatizado o manual?'
        
        echo "git push origin master"
        git push origin master
        
        PULL-REQUEST="hub pull-request -b marceloctorresnet:master -h narceloctorres:master --no-edit -m 'Automatizado' -fp"
        
      env:
        github_token:  ${{ secrets.TOKEN }}
