name: CI - Pull Request from Upstream

on:
  push:
    branches: 
      - master
#  schedule:
#    - cron: "30 0,2,12 * * *"

jobs:
  pull-request:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: marceloctorres/COVID-19 
        path: target
        
    - uses: actions/checkout@v2
      with:
        repository: CSSEGISandData/COVID-19
        path: source
        
    - name: Pull Request .
      run: |
        cd target
        GITHUB_TOKEN=${{ secrets.TOKEN }}
        echo $GITHUB_TOKEN
         
        echo "config --global user.name 'marceloctorres'"
        git config --global user.name 'marceloctorres'

        echo "config --global user.password $GITHUB_TOKEN"
        git config --global user.password m4rc3l025202$$
        
        echo 'git config --global credential.helper store'
        git config --global credential.helper store
        
        echo 'git config --global credential.github.com.useHttpPath true'
        git config --global credential.github.com.useHttpPath true
        
        echo 'git remote -v'
        git remote -v

        echo "git remote set-url origin 'https://marceloctorres:$GITHUB_TOKEN@github.com/marceloctorres/COVID-19.git'"
        git remote set-url origin 'https://marceloctorres:$GITHUB_TOKEN@github.com/marceloctorres/COVID-19.git'
        
        echo "git remote add upstream 'https://CSSEGISandData/COVID-19.git'"
        git remote add upstream 'https://CSSEGISandData/COVID-19.git'
        
        echo "git remote -v"
        git remote -v
        
        echo "hub pr list"
        hub pr list
        
        echo "hub pull-request -b marceloctorres:master -h CCSEGISandData:master --no-edit -m 'Automatizado'"
        hub pull-request -b marceloctorres:master -h CCSEGISandData:master --no-edit -m 'Automatizado'
